
POST https://localhost:7090/api/product
Content-Type: application/json

{
  "name": "Giày thể thao",
  "description": "Giày thể thao thuộc nhãn hàng adidas",
  "price": 40,
  "stockQuantity": 1
}
###